import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import type { BenchSpan, GoldDocument } from "./types";

/**
 * The bench corpus lives with the anonymize regression suite so the
 * same fixtures gate releases and feed the benchmarks. Reference
 * annotations come from the human-reviewed `.snapshot.json` sidecars
 * maintained by contract-snapshots.test.ts.
 */
const CONTRACTS_DIR = join(
  import.meta.dir,
  "..",
  "..",
  "anonymize",
  "src",
  "__test__",
  "fixtures",
  "contracts",
);

type SnapshotFile = {
  entities: BenchSpan[];
};

export const loadGoldDocuments = (): GoldDocument[] => {
  const docs: GoldDocument[] = [];
  for (const language of readdirSync(CONTRACTS_DIR).toSorted()) {
    const languageDir = join(CONTRACTS_DIR, language);
    for (const file of readdirSync(languageDir).toSorted()) {
      if (!file.endsWith(".txt")) continue;
      const text = readFileSync(join(languageDir, file), "utf8").replaceAll(
        "\r\n",
        "\n",
      );
      const snapshotPath = join(
        languageDir,
        file.replace(/\.txt$/u, ".snapshot.json"),
      );
      // SAFETY: sidecars are generated by contract-snapshots.test.ts with this shape
      const snapshot = JSON.parse(
        readFileSync(snapshotPath, "utf8"),
      ) as SnapshotFile;
      docs.push({
        id: `${language}/${file}`,
        language,
        text,
        gold: snapshot.entities.map(({ start, end, label }) => ({
          start,
          end,
          label,
        })),
      });
    }
  }
  return docs;
};
