//! Build-time embedding of the canonical anonymize data config tree.
//!
//! Reads `packages/data/config/*.json` (the mirror-linted canonical source)
//! relative to `CARGO_MANIFEST_DIR` and emits a generated Rust file that maps
//! each data file name to its `include_str!` contents. The generated table is
//! consumed by `crate::assemble::data`.
//!
//! Fails the build with a clear message if the tree is missing so a broken
//! checkout does not silently produce an empty data set.
// `println!` is the sanctioned build-script channel for cargo directives; the
// workspace-wide bans on stdout macros do not apply to build scripts.
#![allow(clippy::print_stdout, clippy::disallowed_macros)]

use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() -> Result<(), Box<dyn Error>> {
  let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
  let config_dir = Path::new(&manifest_dir)
    .join("..")
    .join("..")
    .join("packages")
    .join("data")
    .join("config");
  let config_dir = config_dir.canonicalize().map_err(|error| {
    format!(
      "anonymize data config tree not found at {}: {error}. \
       Expected the mirror-linted canonical source packages/data/config.",
      config_dir.display()
    )
  })?;
  if !config_dir.is_dir() {
    return Err(
      format!(
        "anonymize data config path is not a directory: {}",
        config_dir.display()
      )
      .into(),
    );
  }
  println!("cargo:rerun-if-changed={}", config_dir.display());

  let mut entries: Vec<(String, PathBuf)> = Vec::new();
  for entry in fs::read_dir(&config_dir)? {
    let path = entry?.path();
    if path.extension().and_then(|ext| ext.to_str()) != Some("json") {
      continue;
    }
    let name = path
      .file_name()
      .and_then(|name| name.to_str())
      .ok_or_else(|| {
        format!("non-utf8 data file name under {}", config_dir.display())
      })?
      .to_string();
    println!("cargo:rerun-if-changed={}", path.display());
    entries.push((name, path));
  }
  if entries.is_empty() {
    return Err(
      format!("no JSON data files found in {}", config_dir.display()).into(),
    );
  }
  entries.sort_by(|left, right| left.0.cmp(&right.0));

  let mut generated = String::new();
  generated.push_str(
    "// @generated by build.rs from packages/data/config; do not edit.\n",
  );
  generated.push_str("pub(crate) static DATA_FILES: &[(&str, &str)] = &[\n");
  for (name, path) in &entries {
    // Embed contents as literals rather than include_str!(<absolute path>) so
    // the generated file is hermetic and reproducible across machines.
    let contents = fs::read_to_string(path)
      .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    writeln!(generated, "  ({name:?}, {contents:?}),")?;
  }
  generated.push_str("];\n");

  let out_dir = env::var("OUT_DIR")?;
  let out_path = Path::new(&out_dir).join("assemble_data_generated.rs");
  fs::write(&out_path, generated)?;
  Ok(())
}
